export const appStyles = {
  appContainer: {
    display: 'flex',
    flexDirection: 'row',
    height: '100vh',
    fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
    background: 'linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 50%, #3d3d3d 100%)',
  },
  // Estilos para Login
  loginContainer: {
    display: 'flex',
    height: '100vh',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
  },
  loginWrapper: {
    display: 'flex',
    gap: '4rem',
    alignItems: 'center',
    maxWidth: '1200px',
    width: '100%',
    padding: '2rem',
  },
  loginBrand: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
  },
  loginBrandBox: {
    background: 'linear-gradient(90deg, #FF6F00 0%, #FFB300 50%, #FF9800 100%)',
    borderRadius: '20px',
    padding: '4.5rem',
    marginBottom: '2rem',
    boxShadow: '0 10px 40px rgba(255, 111, 0, 0.3)',
    minWidth: '360px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginLogo: {
    width: '160px',
    height: '160px',
    background: '#7D2BE8',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '4rem',
    marginBottom: '2rem',
    boxShadow: '0 8px 20px rgba(125, 43, 232, 0.4)',
  },
  loginBrandTitle: {
    fontSize: '3.2rem',
    fontWeight: 700,
    marginBottom: '0.5rem',
    letterSpacing: '1px',
  },
  loginBrandSubtitle: {
    fontSize: '1.1rem',
    opacity: 0.9,
    textAlign: 'center',
  },
  loginTagline: {
    fontSize: '1.1rem',
    color: 'rgba(255,255,255,0.9)',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  loginFormBox: {
    flex: 1,
    background: 'rgba(255, 255, 255, 0.95)',
    borderRadius: '16px',
    padding: '4.5rem',
    boxShadow: '0 20px 60px rgba(0, 0, 0, 0.3)',
    minWidth: '450px',
  },
  loginFormTitle: {
    fontSize: '2.4rem',
    color: '#7D2BE8',
    fontWeight: 700,
    marginBottom: '0.5rem',
  },
  loginFormSubtitle: {
    fontSize: '1.05rem',
    color: '#666',
    marginBottom: '2rem',
  },
  loginFormGroup: {
    marginBottom: '1.5rem',
  },
  loginLabel: {
    display: 'block',
    fontSize: '1rem',
    fontWeight: 600,
    color: '#333',
    marginBottom: '0.6rem',
  },
  loginInput: {
    width: '100%',
    padding: '1.2rem 1.2rem',
    border: '2px solid #e0e0e0',
    borderRadius: '8px',
    fontSize: '1.05rem',
    boxSizing: 'border-box',
    transition: 'all 0.3s',
    background: '#f9f9f9',
  },
  loginInputFocus: {
    outline: 'none',
    borderColor: '#7D2BE8',
    background: 'white',
    boxShadow: '0 0 0 3px rgba(125, 43, 232, 0.1)',
  },
  loginButtonGroup: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '1rem',
    marginBottom: '1rem',
  },
  loginButtonClear: {
    padding: '1rem 1.5rem',
    border: 'none',
    borderRadius: '8px',
    fontSize: '1rem',
    fontWeight: 600,
    cursor: 'pointer',
    background: '#EF4444',
    color: 'white',
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
  },
  loginButtonEnter: {
    padding: '1rem 1.5rem',
    border: 'none',
    borderRadius: '8px',
    fontSize: '1rem',
    fontWeight: 600,
    cursor: 'pointer',
    background: '#10B981',
    color: 'white',
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
  },
  loginButtonRegister: {
    width: '100%',
    padding: '1rem 1.5rem',
    border: 'none',
    borderRadius: '8px',
    fontSize: '1rem',
    fontWeight: 600,
    cursor: 'pointer',
    background: '#3B82F6',
    color: 'white',
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
  },
  loginFooter: {
    textAlign: 'center',
    marginTop: '2rem',
    fontSize: '0.85rem',
    color: '#999',
  },
  // Sidebar
  sidebar: {
    width: '240px',
    background: 'linear-gradient(90deg, #FF6F00 0%, #FFB300 50%, #FF9800 100%)',
    color: 'white',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '4px 0 20px rgba(0,0,0,0.25)',
    position: 'relative',
  },
  sidebarHeader: {
    padding: '1.5rem 1.2rem',
    borderBottom: '1px solid rgba(245,243,240,0.15)',
    display: 'flex',
    alignItems: 'center',
    gap: '0.8rem',
  },
  logo: {
    fontSize: '1.8rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'transform 0.3s ease',
  },
  sidebarHeader_h3: {
    fontSize: '1rem',
    fontWeight: 700,
    margin: 0,
    letterSpacing: '0.5px',
    color: '#000000',
    textShadow: '0 2px 4px rgba(0,0,0,0.3)',
  },
  sidebarNav: {
    flex: 1,
    padding: '1rem 0',
    overflowY: 'auto',
  },
  navItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    padding: '0.9rem 1.2rem',
    color: '#000000',
    textShadow: '0 2px 4px rgba(0,0,0,0.3)',
    textDecoration: 'none',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    borderLeft: '3px solid transparent',
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    font: 'inherit',
    width: '100%',
    textAlign: 'left',
    fontSize: '0.95rem',
    position: 'relative',
  },
  navItemActive: {
    background: 'rgba(255, 111, 0, 0.25)',
    color: '#000000',
    textShadow: '0 2px 4px rgba(0,0,0,0.3)',
    borderLeftColor: '#FFD54F',
    boxShadow: 'inset 0 2px 8px rgba(255, 111, 0, 0.15)',
  },
  navIcon: {
    fontSize: '1.2rem',
    minWidth: '24px',
    textAlign: 'center',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sidebarFooter: {
    padding: '1rem 1.2rem',
    borderTop: '1px solid rgba(245,243,240,0.15)',
  },
  logoutBtn: {
    width: '100%',
    padding: '0.6rem 1rem',
    background: 'rgba(255,255,255,0.1)',
    color: '#000000',
    textShadow: '0 2px 4px rgba(0,0,0,0.3)',
    border: '1px solid rgba(255,255,255,0.2)',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '0.9rem',
    fontWeight: 500,
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    justifyContent: 'center',
  },
  // Main Container
  mainContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  topHeader: {
    background: 'linear-gradient(90deg, #FF6F00 0%, #FFB300 50%, #FF9800 100%)',
    borderBottom: '2px solid #FF6F00',
    padding: '1.2rem 2rem',
    display: 'flex',
    alignItems: 'center',
    gap: '1.5rem',
    boxShadow: '0 4px 12px rgba(255, 111, 0, 0.2)',
  },
  searchBar: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    background: 'rgba(255,255,255,0.15)',
    border: '1px solid rgba(255,255,255,0.3)',
    borderRadius: '6px',
    overflow: 'hidden',
    maxWidth: '380px',
  },
  searchInput: {
    flex: 1,
    border: 'none',
    background: 'none',
    padding: '0.6rem 1rem',
    fontSize: '0.95rem',
    color: 'white',
  },
  headerIcons: {
    display: 'flex',
    gap: '0.8rem',
  },
  iconBtn: {
    background: 'none',
    border: 'none',
    fontSize: '1.3rem',
    cursor: 'pointer',
    padding: '0.5rem 0.8rem',
    color: 'white',
    transition: 'all 0.2s',
  },
  // Page Content
  pageContent: {
    display: 'block',
    overflowY: 'auto',
    padding: '2rem',
    background: '#ECEFF1',
  },
  pageHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '2rem',
  },
  pageTitle: {
    fontSize: '1.6rem',
    color: '#000000',
    fontWeight: 700,
    margin: 0,
    textShadow: '0 2px 4px rgba(0,0,0,0.3)',
  },
  btnPrimary: {
    background: 'linear-gradient(90deg, #FF6F00 0%, #FFB300 50%, #FF9800 100%)',
    color: '#1a1a1a',
    border: 'none',
    padding: '0.7rem 1.5rem',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '0.95rem',
    fontWeight: 600,
    transition: 'all 0.2s',
    boxShadow: '0 4px 12px rgba(255, 179, 0, 0.3)',
  },
  // Stats
  statsContainer: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '1rem',
    marginBottom: '2rem',
  },
  statCard: {
    background: 'linear-gradient(90deg, #FF6F00 0%, #FFB300 50%, #FF9800 100%)',
    padding: '1.2rem',
    borderRadius: '8px',
    border: 'none',
    textAlign: 'center',
    boxShadow: '0 4px 12px rgba(255, 111, 0, 0.3)',
    color: '#000000',
  },
  statIcon: {
    fontSize: '1.8rem',
    marginBottom: '0.5rem',
  },
  statLabel: {
    fontSize: '0.85rem',
    color: '#000000',
    marginBottom: '0.5rem',
  },
  statValue: {
    fontSize: '1.6rem',
    fontWeight: 700,
    color: '#000000',
  },
  // Table
  tableContainer: {
    background: '#ECEFF1',
    borderRadius: '8px',
    border: '2px solid #FF6F00',
    overflow: 'hidden',
    boxShadow: '0 6px 16px rgba(255, 111, 0, 0.2)',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    tableLayout: 'fixed',
    fontSize: '0.95rem',
    color: 'white',
  },
  tableHead: {
    background: 'linear-gradient(90deg, #FF6F00 0%, #FFB300 50%, #FF9800 100%)',
    borderBottom: '2px solid #FF6F00',
  },
  tableTh: {
    padding: '1rem',
    textAlign: 'left',
    color: '#000000',
    fontWeight: 600,
    fontSize: '0.9rem',
    letterSpacing: '0.3px',
    textShadow: '0 2px 4px rgba(0,0,0,0.3)',
    verticalAlign: 'middle',
  },
  tableTd: {
    padding: '1rem',
    borderBottom: '1px solid #333333',
    color: '#000000',
    textShadow: '0 2px 4px rgba(0,0,0,0.3)',
    verticalAlign: 'middle',
    overflowWrap: 'anywhere',
  },
  // Badge
  badge: {
    display: 'inline-block',
    padding: '0.35rem 0.7rem',
    borderRadius: '4px',
    fontSize: '0.8rem',
    fontWeight: 600,
  },
  badgeSuccess: {
    background: '#d4edda',
    color: '#155724',
  },
  badgePending: {
    background: '#fff3cd',
    color: '#856404',
  },
  badgeProgress: {
    background: '#cfe2ff',
    color: '#084298',
  },
  // Dishes (POS-style grid)
  dishGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(5, 1fr)',
    gap: '16px',
    padding: '20px',
   // background: '#f5f5f5',
    overflowY: 'auto',
    height: '100%',
    margin: 0,
    justifyContent: 'start',
  },
  dishCard: {
    width: '100%',
    height: '180px',
    border: '2px solid #e0e0e0',
    borderRadius: '8px',
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    background: 'transparent',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
    transition: 'all 0.3s ease',
  },
  dishCardHover: {
    transform: 'translateY(-6px)',
    boxShadow: '0 12px 24px rgba(255, 111, 0, 0.15)',
    borderColor: '#FF6F00',
  },
  dishName: {
    fontSize: '12px',
    textAlign: 'center',
    padding: '8px 6px',
    background: 'linear-gradient(90deg, #FF6F00 0%, #FFB300 50%, #FF9800 100%)',
    color: '#000',
    lineHeight: 1.3,
    margin: 0,
    width: '100%',
    boxSizing: 'border-box',
    fontWeight: 600,
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dishCategory: {
    fontSize: '0.8rem',
    color: '#FF9800',
    marginBottom: '0.8rem',
    fontStyle: 'italic',
  },
  dishPrice: {
    fontSize: '1.1rem',
    fontWeight: 700,
    color: '#4CAF50',
    marginBottom: '0.25rem',
  },
  dishClick: {
    fontSize: '0.85rem',
    color: '#B0B0B0',
    textAlign: 'center',
    marginTop: '0.8rem',
  },
  dishImage: {
    fontSize: '3rem',
    textAlign: 'center',
    marginBottom: '1rem',
  },
  // Modal
  modal: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0, 0, 0, 0.7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  modalContent: {
    background: '#ffffff',
    borderRadius: '12px',
    padding: '1.2rem',
    maxWidth: '380px',
    width: '90%',
    maxHeight: '80vh',
    overflowY: 'auto',
    boxShadow: '0 10px 40px rgba(0, 0, 0, 0.5)',
    border: '2px solid #FF6F00',
  },
  modalClose: {
    float: 'right',
    fontSize: '1.8rem',
    cursor: 'pointer',
    color: '#FF6F00',
    background: 'none',
    border: 'none',
    padding: 0,
  },
  // Ingredients
  ingredientsList: {
    listStyle: 'none',
    padding: 0,
    margin: '0.8rem 0',
  },
  ingredientItem: {
    padding: '0.4rem 0',
    color: '#000000',
    borderBottom: '1px solid rgba(0, 0, 0, 0.1)',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '1rem',
  },
  bullet: {
    color: '#FF6F00',
    fontWeight: 'bold',
  },
  // Categories
  categoryButtons: {
    display: 'flex',
    gap: '0.8rem',
    marginBottom: '2rem',
    flexWrap: 'wrap',
  },
  categoryBtn: {
    padding: '0.7rem 1.2rem',
    border: '2px solid rgba(255, 111, 0, 0.3)',
    background: 'rgba(255, 255, 255, 0.8)',
    color: '#000000',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '0.95rem',
    fontWeight: 600,
    transition: 'all 0.3s ease',
    display: 'flex',
    alignItems: 'center',
    gap: '0.6rem',
    transform: 'scale(1)',
  },
  categoryBtnActive: {
    background: 'linear-gradient(90deg, #FF6F00 0%, #FFB300 50%, #FF9800 100%)',
    color: '#000000',
    border: '2px solid #FF6F00',
    boxShadow: '0 4px 12px rgba(255, 111, 0, 0.3)',
    transform: 'scale(1.05)',
  },
  // Placeholder empty card to keep grid uniform
  placeholderCard: {
    width: '150px',
    height: '150px',
    background: '#ffffff',
    border: '1px dashed #e9e9e9',
    borderRadius: '4px',
  },
}


export const moduleBackgrounds = {
  comandas: '#ECEFF1',      
  menu: '#ECEFF1',          
  pagos: '#ECEFF1',         
}
